sudo: required
before_install:
  - sudo apt-get install libsdl2-dev libsdl2-2.0 libsdl2-image libsdl2-image-dev

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - g++

# Build steps
script:
  - make