sudo: required
before_install:
  - sudo apt-get install libsdl1.2-dev libsdl1.2-2.0 libsdl1.2-image libsdl1.2-image-dev

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - g++

# Build steps
script:
  - make